### ISSUE TITLE
原Appdelegate方法调用者被换了

### ISSUE THREAD

**Issue by icofans** [TryRuntime/UCAppDelegateReduce#6]
在 Appdelegate中方法调用者变成了 UCAppDelegateRealize，即在Appdelegate的原方法使用self都是有问题的

**Comment by harofan** [comment]
对的,所以这里利用了runtime

    /// 向原来的delegate添加所有方法
    - (void)p_addAllMethodOriginAppdelegateName:(NSString *)originalAppdelegateName
                                        error:(NSError * __autoreleasing *)error {
        
        // 添加调用原来delegate的一个方法
        [self p_addMethodOriginalAppdelegateName:originalAppdelegateName
                                      methodName:kUCAppDelegateReduceInvokeOriginDelegateMethod
                                           error:error];
        // 添加派发各个模块的方法
        [self p_addMethodOriginalAppdelegateName:originalAppdelegateName
                                      methodName:kUCAppDelegateReduceSendNewDelegateMethod
                                           error:error];
    }

先向原来的delegate添加了两个空方法,然后直接交换`IMP`,这样子就能在xcode有提示的情况下在我们封装的工具中调用到方法了

**Comment by icofans** [comment]
我现在想在Appdelegate去使用self.window 这个时候self被交换了，我该怎么做

**Comment by icofans** [comment]
有QQ吗

**Comment by harofan** [comment]
我的主工程是没有代码的, 这样子的需求我一般会在全局区写一个

    static UIWindow *gWindow = nil;

**Comment by icofans** [comment]
有QQ吗，我有点问题现在没想明白

**Comment by harofan** [comment]
969408938

**Comment by SparkChenZ** [comment]
这个问题有办法解决吗

**Comment by icofans** [comment]
没有同意，加下我把，我的是 565057208
